### ISSUE TITLE
publikator: "unexpected error" if you press tab key several times

### ISSUE THREAD

**Issue by eightam** [orbiting/backends#119]
## Bug Report
On a front in Publikator, if you use the tab key an "unexpected error" occurs.

**Steps to Reproduce**
1. Try it on staging in /repo/republik-dev/zukunft/.
2. Click into the wysiwyg
3. Press tab several times

**Environment**
- OS: OSX 10.14
- Chrome: 69.0.3497.100

**Comment by patte** [comment]
@eightam thank you for the issue Nick! I'm sorry for it. But as this is a frontend bug (it happens in your browser, not on our servers) this is the wrong repo for this, it should go here: https://github.com/orbiting/publikator-frontend/issues. Can you please reopen it there?
