### ISSUE TITLE
publikator: Can't edit "image only" in teaser column

### ISSUE THREAD

**Issue by eightam** [orbiting/backends#120]
## Bug Report
As soon as a teaser column is activated as "Nur Bild", editing is not possible anymore.

**Steps to Reproduce**
1. Try this version: https://publikator.republik.love/repo/republik-dev/zukunft/edit?commitId=1614d7d4f94e64a2a5e41ac95c968e5450681713
2. The photo on the top right is not editable anymore.
3. Click into another column, choose "Nur Bild".
4. Now you can't click that column anymore.

**Environment**
- OS: OSX 10.14
- Chrome: 69.0.3497.100

**Comment by patte** [comment]
@eightam thank you for the issue Nick! I'm sorry for it. But as this is a frontend bug (it happens in your browser, not on our servers) this is the wrong repo for this, it should go here: https://github.com/orbiting/publikator-frontend/issues. Can you please reopen it there?

**Comment by eightam** [comment]
Then my other issue is in the wrong repo as well ... sorry for that.

**Comment by patte** [comment]
no problem. Thank you very much for the effort!
