### ISSUE TITLE
Several problems while running the application

### ISSUE THREAD

**Issue by dvladir** [orbiting/backends#248]
## Bug Report

**Steps to Reproduce**

I installed a web application according to [how-to-run](https://github.com/orbiting/docs/blob/master/guides/how-to-run.md) guide. Successfully added a new user. But when I go to the profile, I see the following:

**Actual Results**

![screen-shot](https://user-images.githubusercontent.com/16287112/56963417-8b06f700-6b61-11e9-90b7-984b252d05e8.png)

Also the log contains a stack-trace:
[republik.log](https://github.com/orbiting/backends/files/3131340/republik.log)

**Environment**

- Node 10.15.3/yarn 1.9.4
- PostgreSQL 11.2-3
- Redis 4.0.9
- Elasticsearch 6.7.0
- OS: Arch Linux (Kernel 5.0.10)

Please, can you check it out and tell what is running wrong in my case. Thank you.

**Comment by patte** [comment]
Dear @dvladir thank you for the reporting this. There is an issue with applying all migrations when starting from scratch. The following PR fixes this: https://github.com/orbiting/backends/pull/224
It should get merged very soon.

**Comment by patte** [comment]
Dear @dvladir! The big refactoring PRs have been merged and I updated this repos readme and also [docs/how-to-run](https://github.com/orbiting/docs/blob/master/guides/how-to-run.md) to unify and simplify the setup instructions. It should now be pretty simple to get all of republiks core services up and running locally. Please tell me if it works for you.
