### ISSUE TITLE
Usage with crowdfunding frontend

### ISSUE THREAD

**Issue by markushausammann** [orbiting/backends#28]
Hi, can this still be used as crowdfunding backend together with the crowdfunding frontend? And also, how? :)

**Comment by tpreusse** [comment]
Hi Markus, sorry for the late response. In theory yes, we're working on writing how to run guide and other introductions. Watch [orbiting/docs](https://github.com/orbiting/docs) for updates.

However if you're using [orbiting/crowdfunding-frontend](https://github.com/orbiting/crowdfunding-frontend) as a starting point you're probably better off using the companion [crowdfunding-backend](https://github.com/orbiting/crowdfunding-backend)—it provides 100% of the API used in the frontend.

**Comment by markushausammann** [comment]
Ok, but the backend is read-only and says DEPRECATED. Is it still ok to use?

**Comment by tpreusse** [comment]
We won't update it anymore from our side and we can not guarantee anything or take any liability for any of our software. But if you fork it, you run it with the latest stable node.js version and update packages with security warnings (you'll see those after forking, if any) you should be fine.
