### ISSUE TITLE
Trouble installing the backend on linux

### ISSUE THREAD

**Issue by dneise** [orbiting/backends#287]
Hey there, 

(do you prefer english or german? I am german, but github issues, seem to prefer english)

thanks for developing your stack open source. I am basically a noob, trying to get this running on my laptop in order to learn. I do this, since the fridays for future people, in particular the netto.null group seemed interested... again not an expert here at all.

So I followed the [how-to-run in the docs](https://github.com/orbiting/docs/blob/master/guides/how-to-run.md) and started by trying to setup the [backend README](https://github.com/orbiting/backends/blob/master/README.md). 

(installing yarn on ubuntu 18.04 was a bit of a hassle due to `cmdtest` ... but I think I got it running after all)

I am stuck at [point 4 init](https://github.com/orbiting/backends/blob/master/README.md#4-initialize) `yarn run db:migrate:up` returned this error msg:
```
(base) ✔ ~/climate_strike/netto.null_website/backends [master|✔] 
10:05 $ yarn run db:migrate:up
yarn run v1.16.0
error @orbiting/backends@1.0.0: The engine "node" is incompatible with this module. Expected version "12.x". Got "10.16.0"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

(base) ✘-1 ~/climate_strike/netto.null_website/backends [master|✔] 
10:05 $ node --version
v10.16.0
```

So indeed my node version is 10.16 , while something somewhere expects 12.x ... I do not understand where I messed this up? Is there a more recent version of node running inside one of the docker containers? 

Do you have any idea how to proceed? Should I just try to update my host node to 12.x and start over from scratch? 

Thanks a lot for your great work.

**Comment by patte** [comment]
Hi dneise
I personally perfer english as many programming related sources are english. Thanks for the issue. Nice to see other projects being interested in our software.

What you describe is yarn complaining about your local node version (10.x) not matching what's specified in [package.json](https://github.com/orbiting/backends/blob/master/package.json#L8)'s engine field.
You have two choices:
- run yarn commands with `--ignore-engines` [docs](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-engines). Everything should work with node 10, so this is the fastest option for trying out the software.
- upgrade to node 12. I personally manage the node installation with [nvm](https://github.com/nvm-sh/nvm)

Let me now if you get it to run.

**Comment by dneise** [comment]
Hey Patrick thanks for answering during the weekend! That's awesome!

I've upgraded node to v12.6.0 using nvm. Then I got a few issues about mismatching versions. So I wiped everything and started from the beginning.

This time I got up to [point 5](https://github.com/orbiting/backends/blob/master/README.md#5-run) \o/.
But assets, publikator and republik all report: `[nodemon] app crashed - waiting for file changes before starting...` 

Details can be found here [yarn_run_def__log_out.txt](https://github.com/orbiting/backends/files/3388774/yarn_run_def__log_out.txt) but I've got the impression this is connected with missing `AWS_ACCESS_KEY_ID` and/or `AWS_SECRET_ACCESS_KEY` in the `.env` files. 
Did I understand correctly, that local testing without using AWS should be possible?

----

I kind of expected some issues at this point, but I still tried to access: 
 * `http://localhost:5000/graphiql`
 * `http://localhost:5010/graphiql`
 * `http://localhost:5020/`

but no server was running on either of these ports, is that correct so far?

Thanks for your help

**Comment by tpreusse** [comment]
The code enforced that an `AWS_S3_BUCKET` is set. The other `AWS_*` were already optional.

I pushed a [change to make it optional](https://github.com/orbiting/backends/commit/9d7eb7ae4c5eae76f66c2340a96df0828b843cd5), pull the master and try run `yarn dev run` again.

**Comment by dneise** [comment]
Thanks Thomas! That worked like a charm ... the servers are running nicely. I guess we could close this issue and I'll open new issues in case I run into different problems?

**Comment by tpreusse** [comment]
Glad it worked. Yeah, let's close this one. We're flattered that you are considering using our code. Please do open issues when other problems arise. We'll try to help the best we can.
