### ISSUE TITLE
Buggy Mandrill HTML to Text conversation

### ISSUE THREAD

**Issue by tpreusse** [orbiting/backends#298]
```
      Sie erhalten diese E-Mail, weil Sie an der Debatte =C2=ABD=C3=BCrfen =
wir mehr
=C3=BCber Ihr Verhalten wissen?
<https://www.republik.ch/dialog?id=3D57e2e394-f269-4244-9678-6a62a6cce99a&a=
mp;t=3Darticle>=C2=BB
teilgenommen haben und/oder Benachrichtigungen f=C3=BCr diese abonniert hab=
en. 
```

Should be:

```
      Sie erhalten diese E-Mail, weil Sie an der Debatte =C2=ABD=C3=BCrfen =
wir mehr
=C3=BCber Ihr Verhalten wissen?
<https://www.republik.ch/dialog?id=3D57e2e394-f269-4244-9678-6a62a6cce99a&t=
=3Darticle>=C2=BB
teilgenommen haben und/oder Benachrichtigungen f=C3=BCr diese abonniert hab=
en. 
```

Mandrills converter fails to convert `&amp;` to `&` when extracting hrefs from the html version. In HTML attributes like href `&` should be encoded as `&amp;` but in plain text obviously not. This is a bug in Mandrills `auto_text` converter.

Possible solution:
- write our own converter and send precomputed plain text version
- maintain all emails as plain text too

Possible workaround:
- skip `&amp;` encoding in `href`s, most likely most html parser could handle it. But this would not be spec conform (`{{{URL}}}` instead of `{{URL}}` in handlebar templates).

**Comment by stefonarch** [comment]
Same here, affects login link token when using plain text in mailprogram (thunderbird), login impossible.
![schermata-27-14-02-12](https://user-images.githubusercontent.com/10681413/75465124-79140180-5988-11ea-9acf-9e18a3184680.png)

**Comment by tpreusse** [comment]
We'll work on a proper fix next week. But in the meantime I've added some frontend code to shown an error when an incomplete link is clicked and try to clean and fix the url if possible (all the data was copied or somehow ended up in an url bar):
https://github.com/orbiting/republik-frontend/commit/2e9ce4a97e1230f48585e4a9ae9b7d4c24f4def4#diff-591bceec23193267b66c68b159133e2aR116-R124
