### ISSUE TITLE
Sign-in-Link does not work with certain Web-mail-clients

### ISSUE THREAD

**Issue by sirtobey** [orbiting/backends#38]
## Bug Report

I have recently changed my email address for my Republik-Account to one using Open Exchange Web Frontend. There, the Sign-in-Link is encoded wrong and is invalid:
`https://www.republik.ch/mitteilung?type=token-authorization&email=mail.address%**2540**provider.ch&context=signIn&token=TOKEN`

The issue lies with the double encoded @. I am uncertain, if this could be an issue with OX Web or the link, as it used to work on Gmail.

**Steps to Reproduce**

1. Sign out
2. Login with Email
3. Click link in OX Web mail client

**Actual Results**
`https://www.republik.ch/mitteilung?type=token-authorization&email=mail.address%2540provider.ch&context=signIn&token=TOKEN`

**Expected Results**
`https://www.republik.ch/mitteilung?type=token-authorization&email=mail.address%40provider.ch&context=signIn&token=TOKEN`

**Environment**
- OS: Fedora 27
- Firefox 59.0.2 (64-bit)
- UI version: 7.8.4 Rev28
- Server version: 7.8.4-Rev29

**Possible Solutions**

**Comment by sirtobey** [comment]
Should it be an issue with OX Web, I will gladly close this issue and open a bug report on OX Web. However, I haven't experianced encoding-broken links yet there (it has other issues)

**Comment by patrickvenetz** [comment]
Excellent find.

We did stumple upon that very same issue a day ago.

There is a fix underway, resulting in these Merge Requests:

* Server/API part: https://github.com/orbiting/backends/pull/37
* Frontend: https://github.com/orbiting/republik-frontend/pull/101

**Comment by sirtobey** [comment]
Oh, sorry, I only checked the open issues, not pull requests.

**Comment by patte** [comment]
No need for sorry, thank you for the awesome issue!

**Comment by patrickvenetz** [comment]
Apart from aforementioned Merge Requests and an initial attempt, we did decide to have email addresses decoded in `pages/notifications`.
* see https://github.com/orbiting/republik-frontend/pull/101

Server/API is soley responsible to encode email address in a base64, URL safe manner when generating verification links but expects API requests to be plain:
* Server/API: https://github.com/orbiting/backends/pull/41

Both Merge Request are available in their repos master branches now.

**Comment by patrickvenetz** [comment]
@sirtobey Would you be so kind to verify if this issue still persists on republik.ch for you?

**Comment by sirtobey** [comment]
I have tested it on my Windows 10 machine and it seems to work. I can try it on Linux on monday if you like.
