### ISSUE TITLE
Forward HTTP Status Code for GitHub in Asset Server

### ISSUE THREAD

**Issue by tpreusse** [orbiting/backends#419]
## Bug Report

E.g. 404 get cached in the cdn because the status code is not forwarded:

https://cdn.repub.ch/github/republik/article-wdwww-01-05/images/f859740c39115c2bafcd4929da5bf65f6a29e59c.jpeg?size=2864x1909
is a 404 but asset backend returns a 200.

Somehow a bad credentials request – probably a 400 – was cached as a 200 and prevented a image from showing up correctly in publikator even after a while. Directly requesting it worked (assets instead of cdn). If the error would have been properly handled it would have self healed. Now I had to manually clean the cdn cache for that url.

**Comment by tpreusse** [comment]
Make sure to check for similar issue in the s3 code.

**Comment by tpreusse** [comment]
happened again today with a different image. probably some race condition with github.

**Comment by patrickvenetz** [comment]
Happened once more with bad credentials in response.

**Comment by patte** [comment]
fixed by https://github.com/orbiting/backends/pull/431
All other asset endpoints had the checks of upstream content in place.
