### ISSUE TITLE
Normalize mailLog table

### ISSUE THREAD

**Issue by caillou** [orbiting/backends#505]
As of now, the `mailLog` table identifies a user by their e-mail address.

This leads to errors, when users change their addresses.

Refactor the `mailLog` to user the users' `id` rather than the e-mail address.

**Comment by patte** [comment]
Dear @caillou 
`mailLog` sports both an `email` and `userId` column if I remember correctly. The reasoning to have both was to be able to track where emails where sent to exactly and to be able to keep the records if a user gets deleted.
Cheers

**Comment by caillou** [comment]
@patte you are right, I missed the `userId` field, as it always has `NULL` values for the types of requests I looked at ;)

Closing this in favour of https://github.com/orbiting/backends/issues/506
