### ISSUE TITLE
Mutations for November 2020 Urabstimmung

### ISSUE THREAD

**Issue by annatraussnig** [orbiting/backends#530]
1. [Wollen Sie den Geschäftsbericht 2019/2020 annehmen?](https://api.republik.love/graphiql/?query=mutation%20%7B%0A%20%20createVoting(votingInput%3A%20%7B%0A%20%20%20%20name%3A%20%22gen202011-1%22%0A%20%20%20%20slug%3A%20%22gen202011-1%22%0A%20%20%20%20description%3A%20%22Wollen%20Sie%20den%20Gesch%C3%A4ftsbericht%202019%2F2020%20annehmen%3F%22%0A%20%20%20%20beginDate%3A%20%222020-11-09%22%0A%20%20%20%20endDate%3A%20%222020-11-23%22%0A%20%20%20%20allowEmptyBallots%3A%20true%0A%20%20%20%20allowedRoles%3A%20%5B%22gen202011%22%5D%0A%20%20%20%20groupSlug%3A%20%22gen202011%22%0A%20%20%20%20options%3A%20%5B%0A%20%20%20%20%20%20%7Bname%3A%20%22YES%22%20label%3A%20%22YES%22%20description%3A%20%22YES%22%7D%0A%20%20%20%20%20%20%7Bname%3A%20%22NO%22%20label%3A%20%22NO%22%20description%3A%20%22NO%22%7D%0A%20%20%20%20%5D%0A%20%20%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20slug%0A%20%20%20%20description%0A%20%20%20%20beginDate%0A%20%20%20%20endDate%0A%20%20%20%20options%20%7Bid%20name%20label%20description%7D%0A%20%20%20%20userIsEligible%0A%20%20%20%20userHasSubmitted%0A%20%20%20%20userSubmitDate%0A%20%20%20%20allowedRoles%0A%20%20%20%20allowedMemberships%7BmembershipTypeId%20createdBefore%7D%0A%20%20%20%20allowedRoles%0A%20%20%20%20groupSlug%0A%20%20%20%20name%0A%20%20%20%20discussion%20%7Bid%20title%7D%0A%20%20%20%20turnout%7Beligible%20submitted%7D%0A%20%20%20%20groupTurnout%7Beligible%20submitted%7D%0A%20%20%20%20liveResult%0A%20%20%20%20result%20%7Boptions%7Boption%7Bname%7D%20count%20winner%7D%7D%0A%20%20%7D%0A%7D)
2. [Wollen Sie die Jahresrechnung 2019/2020 annehmen?](https://api.republik.love/graphiql/?query=mutation%20%7B%0A%20%20createVoting(votingInput%3A%20%7B%0A%20%20%20%20name%3A%20%22gen202011-2%22%0A%20%20%20%20slug%3A%20%22gen202011-2%22%0A%20%20%20%20description%3A%20%22Wollen%20Sie%20die%20Jahresrechnung%202019%2F2020%20annehmen%3F%22%0A%20%20%20%20beginDate%3A%20%222020-11-09%22%0A%20%20%20%20endDate%3A%20%222020-11-23%22%0A%20%20%20%20allowEmptyBallots%3A%20true%0A%20%20%20%20allowedRoles%3A%20%5B%22gen202011%22%5D%0A%20%20%20%20groupSlug%3A%20%22gen202011%22%0A%20%20%20%20options%3A%20%5B%0A%20%20%20%20%20%20%7Bname%3A%20%22YES%22%20label%3A%20%22YES%22%20description%3A%20%22YES%22%7D%0A%20%20%20%20%20%20%7Bname%3A%20%22NO%22%20label%3A%20%22NO%22%20description%3A%20%22NO%22%7D%0A%20%20%20%20%5D%0A%20%20%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20slug%0A%20%20%20%20description%0A%20%20%20%20beginDate%0A%20%20%20%20endDate%0A%20%20%20%20options%20%7Bid%20name%20label%20description%7D%0A%20%20%20%20userIsEligible%0A%20%20%20%20userHasSubmitted%0A%20%20%20%20userSubmitDate%0A%20%20%20%20allowedRoles%0A%20%20%20%20allowedMemberships%7BmembershipTypeId%20createdBefore%7D%0A%20%20%20%20allowedRoles%0A%20%20%20%20groupSlug%0A%20%20%20%20name%0A%20%20%20%20discussion%20%7Bid%20title%7D%0A%20%20%20%20turnout%7Beligible%20submitted%7D%0A%20%20%20%20groupTurnout%7Beligible%20submitted%7D%0A%20%20%20%20liveResult%0A%20%20%20%20result%20%7Boptions%7Boption%7Bname%7D%20count%20winner%7D%7D%0A%20%20%7D%0A%7D)
3. [Wollen Sie dem Vorstand für das Geschäftsjahr 2019/2020 die Entlastung erteilen?](https://api.republik.love/graphiql/?query=mutation%20%7B%0A%20%20createVoting(votingInput%3A%20%7B%0A%20%20%20%20name%3A%20%22gen202011-3%22%0A%20%20%20%20slug%3A%20%22gen202011-3%22%0A%20%20%20%20description%3A%20%22Wollen%20Sie%20dem%20Vorstand%20f%C3%BCr%20das%20Gesch%C3%A4ftsjahr%202019%2F2020%20die%20Entlastung%20erteilen%3F%22%0A%20%20%20%20beginDate%3A%20%222020-11-09%22%0A%20%20%20%20endDate%3A%20%222020-11-23%22%0A%20%20%20%20allowEmptyBallots%3A%20true%0A%20%20%20%20allowedRoles%3A%20%5B%22gen202011%22%5D%0A%20%20%20%20groupSlug%3A%20%22gen202011%22%0A%20%20%20%20options%3A%20%5B%0A%20%20%20%20%20%20%7Bname%3A%20%22YES%22%20label%3A%20%22YES%22%20description%3A%20%22YES%22%7D%0A%20%20%20%20%20%20%7Bname%3A%20%22NO%22%20label%3A%20%22NO%22%20description%3A%20%22NO%22%7D%0A%20%20%20%20%5D%0A%20%20%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20slug%0A%20%20%20%20description%0A%20%20%20%20beginDate%0A%20%20%20%20endDate%0A%20%20%20%20options%20%7Bid%20name%20label%20description%7D%0A%20%20%20%20userIsEligible%0A%20%20%20%20userHasSubmitted%0A%20%20%20%20userSubmitDate%0A%20%20%20%20allowedRoles%0A%20%20%20%20allowedMemberships%7BmembershipTypeId%20createdBefore%7D%0A%20%20%20%20allowedRoles%0A%20%20%20%20groupSlug%0A%20%20%20%20name%0A%20%20%20%20discussion%20%7Bid%20title%7D%0A%20%20%20%20turnout%7Beligible%20submitted%7D%0A%20%20%20%20groupTurnout%7Beligible%20submitted%7D%0A%20%20%20%20liveResult%0A%20%20%20%20result%20%7Boptions%7Boption%7Bname%7D%20count%20winner%7D%7D%0A%20%20%7D%0A%7D)
4. [Wollen Sie das Project-R-Budget 2020/2021 annehmen?](https://api.republik.love/graphiql/?query=mutation%20%7B%0A%20%20createVoting(votingInput%3A%20%7B%0A%20%20%20%20name%3A%20%22gen202011-4%22%0A%20%20%20%20slug%3A%20%22gen202011-4%22%0A%20%20%20%20description%3A%20%22Wollen%20Sie%20das%20Project-R-Budget%202020%2F2021%20annehmen%3F%22%0A%20%20%20%20beginDate%3A%20%222020-11-09%22%0A%20%20%20%20endDate%3A%20%222020-11-23%22%0A%20%20%20%20allowEmptyBallots%3A%20true%0A%20%20%20%20allowedRoles%3A%20%5B%22gen202011%22%5D%0A%20%20%20%20groupSlug%3A%20%22gen202011%22%0A%20%20%20%20options%3A%20%5B%0A%20%20%20%20%20%20%7Bname%3A%20%22YES%22%20label%3A%20%22YES%22%20description%3A%20%22YES%22%7D%0A%20%20%20%20%20%20%7Bname%3A%20%22NO%22%20label%3A%20%22NO%22%20description%3A%20%22NO%22%7D%0A%20%20%20%20%5D%0A%20%20%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20slug%0A%20%20%20%20description%0A%20%20%20%20beginDate%0A%20%20%20%20endDate%0A%20%20%20%20options%20%7Bid%20name%20label%20description%7D%0A%20%20%20%20userIsEligible%0A%20%20%20%20userHasSubmitted%0A%20%20%20%20userSubmitDate%0A%20%20%20%20allowedRoles%0A%20%20%20%20allowedMemberships%7BmembershipTypeId%20createdBefore%7D%0A%20%20%20%20allowedRoles%0A%20%20%20%20groupSlug%0A%20%20%20%20name%0A%20%20%20%20discussion%20%7Bid%20title%7D%0A%20%20%20%20turnout%7Beligible%20submitted%7D%0A%20%20%20%20groupTurnout%7Beligible%20submitted%7D%0A%20%20%20%20liveResult%0A%20%20%20%20result%20%7Boptions%7Boption%7Bname%7D%20count%20winner%7D%7D%0A%20%20%7D%0A%7D)
5. [Wollen Sie den Wahlvorschlag für die Revisionsstelle annehmen?](https://api.republik.love/graphiql/?query=mutation%20%7B%0A%20%20createVoting(votingInput%3A%20%7B%0A%20%20%20%20name%3A%20%22gen202011-5%22%0A%20%20%20%20slug%3A%20%22gen202011-5%22%0A%20%20%20%20description%3A%20%22Wollen%20Sie%20den%20Wahlvorschlag%20f%C3%BCr%20die%20Revisionsstelle%20annehmen%3F%22%0A%20%20%20%20beginDate%3A%20%222020-11-09%22%0A%20%20%20%20endDate%3A%20%222020-11-23%22%0A%20%20%20%20allowEmptyBallots%3A%20true%0A%20%20%20%20allowedRoles%3A%20%5B%22gen202011%22%5D%0A%20%20%20%20groupSlug%3A%20%22gen202011%22%0A%20%20%20%20options%3A%20%5B%0A%20%20%20%20%20%20%7Bname%3A%20%22YES%22%20label%3A%20%22YES%22%20description%3A%20%22YES%22%7D%0A%20%20%20%20%20%20%7Bname%3A%20%22NO%22%20label%3A%20%22NO%22%20description%3A%20%22NO%22%7D%0A%20%20%20%20%5D%0A%20%20%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20slug%0A%20%20%20%20description%0A%20%20%20%20beginDate%0A%20%20%20%20endDate%0A%20%20%20%20options%20%7Bid%20name%20label%20description%7D%0A%20%20%20%20userIsEligible%0A%20%20%20%20userHasSubmitted%0A%20%20%20%20userSubmitDate%0A%20%20%20%20allowedRoles%0A%20%20%20%20allowedMemberships%7BmembershipTypeId%20createdBefore%7D%0A%20%20%20%20allowedRoles%0A%20%20%20%20groupSlug%0A%20%20%20%20name%0A%20%20%20%20discussion%20%7Bid%20title%7D%0A%20%20%20%20turnout%7Beligible%20submitted%7D%0A%20%20%20%20groupTurnout%7Beligible%20submitted%7D%0A%20%20%20%20liveResult%0A%20%20%20%20result%20%7Boptions%7Boption%7Bname%7D%20count%20winner%7D%7D%0A%20%20%7D%0A%7D)
6. [Wollen Sie den Vorstand für ein Jahr bestätigen?](https://api.republik.love/graphiql/?query=mutation%20%7B%0A%20%20createVoting(votingInput%3A%20%7B%0A%20%20%20%20name%3A%20%22gen202011-6%22%0A%20%20%20%20slug%3A%20%22gen202011-6%22%0A%20%20%20%20description%3A%20%22Wollen%20Sie%20den%20Vorstand%20f%C3%BCr%20ein%20Jahr%20best%C3%A4tigen%3F%22%0A%20%20%20%20beginDate%3A%20%222020-11-09%22%0A%20%20%20%20endDate%3A%20%222020-11-23%22%0A%20%20%20%20allowEmptyBallots%3A%20true%0A%20%20%20%20allowedRoles%3A%20%5B%22gen202011%22%5D%0A%20%20%20%20groupSlug%3A%20%22gen202011%22%0A%20%20%20%20options%3A%20%5B%0A%20%20%20%20%20%20%7Bname%3A%20%22YES%22%20label%3A%20%22YES%22%20description%3A%20%22YES%22%7D%0A%20%20%20%20%20%20%7Bname%3A%20%22NO%22%20label%3A%20%22NO%22%20description%3A%20%22NO%22%7D%0A%20%20%20%20%5D%0A%20%20%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20slug%0A%20%20%20%20description%0A%20%20%20%20beginDate%0A%20%20%20%20endDate%0A%20%20%20%20options%20%7Bid%20name%20label%20description%7D%0A%20%20%20%20userIsEligible%0A%20%20%20%20userHasSubmitted%0A%20%20%20%20userSubmitDate%0A%20%20%20%20allowedRoles%0A%20%20%20%20allowedMemberships%7BmembershipTypeId%20createdBefore%7D%0A%20%20%20%20allowedRoles%0A%20%20%20%20groupSlug%0A%20%20%20%20name%0A%20%20%20%20discussion%20%7Bid%20title%7D%0A%20%20%20%20turnout%7Beligible%20submitted%7D%0A%20%20%20%20groupTurnout%7Beligible%20submitted%7D%0A%20%20%20%20liveResult%0A%20%20%20%20result%20%7Boptions%7Boption%7Bname%7D%20count%20winner%7D%7D%0A%20%20%7D%0A%7D)
7. [Wollen Sie die Statutenänderung annehmen?](https://api.republik.love/graphiql/?query=mutation%20%7B%0A%20%20createVoting(votingInput%3A%20%7B%0A%20%20%20%20name%3A%20%22gen202011-7%22%0A%20%20%20%20slug%3A%20%22gen202011-7%22%0A%20%20%20%20description%3A%20%22Wollen%20Sie%20die%20Statuten%C3%A4nderung%20annehmen%3F%22%0A%20%20%20%20beginDate%3A%20%222020-11-09%22%0A%20%20%20%20endDate%3A%20%222020-11-23%22%0A%20%20%20%20allowEmptyBallots%3A%20true%0A%20%20%20%20allowedRoles%3A%20%5B%22gen202011%22%5D%0A%20%20%20%20groupSlug%3A%20%22gen202011%22%0A%20%20%20%20options%3A%20%5B%0A%20%20%20%20%20%20%7Bname%3A%20%22YES%22%20label%3A%20%22YES%22%20description%3A%20%22YES%22%7D%0A%20%20%20%20%20%20%7Bname%3A%20%22NO%22%20label%3A%20%22NO%22%20description%3A%20%22NO%22%7D%0A%20%20%20%20%5D%0A%20%20%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20slug%0A%20%20%20%20description%0A%20%20%20%20beginDate%0A%20%20%20%20endDate%0A%20%20%20%20options%20%7Bid%20name%20label%20description%7D%0A%20%20%20%20userIsEligible%0A%20%20%20%20userHasSubmitted%0A%20%20%20%20userSubmitDate%0A%20%20%20%20allowedRoles%0A%20%20%20%20allowedMemberships%7BmembershipTypeId%20createdBefore%7D%0A%20%20%20%20allowedRoles%0A%20%20%20%20groupSlug%0A%20%20%20%20name%0A%20%20%20%20discussion%20%7Bid%20title%7D%0A%20%20%20%20turnout%7Beligible%20submitted%7D%0A%20%20%20%20groupTurnout%7Beligible%20submitted%7D%0A%20%20%20%20liveResult%0A%20%20%20%20result%20%7Boptions%7Boption%7Bname%7D%20count%20winner%7D%7D%0A%20%20%7D%0A%7D)

## Clarify

- For the `Voting` to finish 22.11 at 23:59, `endDate` should be `23.11`I assume.

_Queries are currently linked to *LOVE* but should be run on production. Test voting running 3.11 to 4.11 on LOVE is called `gen202011-{1-7}`_

**Comment by annatraussnig** [comment]
Thanks for having a look and giving feedback 🙇‍♀️

**Comment by patrickvenetz** [comment]
About `allowedRoles: ["associate"]`:

We did set a dedicated role in the past, e.g. `gen201912`, to lock those who are allowed.

This would prevent users from participating in votings if they signed up after voting began. Helped avoiding issues like having enough time to inform yourself and vote or avoid malicious signups to influence voting, et al.

As @tpreusse mentioned before, it is a bit quirky to add new roles. There are a bunch by now.

Yet, I would lean towards creating a dedicated user role (like a sticker, allowing you to vote). I shall take it onto myself to list and remove obsolete roles after this vote. I would prep a query which would append a role, say `gen202011`, and mutations would have to be updated to `allowedRoles: ["gen202011"]`.

(We can circumvent all of this, of course, if Philipp says that all doesn't matter to us and we could handle resulting issues differently.)

**Comment by annatraussnig** [comment]
Sounds good following the discussion with Philipp... I think he wants to keep the numbers/goals etc. stable throughout the election

**Comment by annatraussnig** [comment]
Will you help me with the role/permissions then?

**Comment by patrickvenetz** [comment]
Surley – if even necessary. We'll settle on this tomorrow.

**Comment by tpreusse** [comment]
My suggestion is to use the mechanism original design for that:
```
    allowedMemberships: [
      {membershipTypeId: "8ecd1d10-1519-4382-a401-5ec10bbec181" createdBefore: "2020-11-06"}
      {membershipTypeId: "ef0f787a-34b5-4494-80f6-18831799aaaa" createdBefore: "2020-11-06"}
    ]
```
See guide by Patte: https://github.com/orbiting/docs/blob/master/guides/create-urabstimmung.md

**Comment by patrickvenetz** [comment]
That failed since it checks `membership.createdAt` date and not period begin. Once previously bought memberships were claimed within voting period, it altered total count of users allowed to vote.

Still opting for a (pre-calculated) role instead of formulaic approach as I see no actual downside to it (apart from lack of a mutation to generate such a role and, obviously, an abundance of roles).

**Comment by patrickvenetz** [comment]
Another upside for role: segment is easily retrievable for bulk mailings.

**Comment by patrickvenetz** [comment]
> - For the `Voting` to finish 22.11 at 23:59, `endDate` should be `23.11`I assume.

That is [a fair assumption](https://github.com/orbiting/backends/blob/master/packages/voting/lib/queries.js#L279-L281).

**Comment by patrickvenetz** [comment]
We're proceeding with a new role, `gen202011`.

This role will added to users which have a membership which began before November 6 (and ends after). Eligiable count is settle Friday morning when running that query and I shall take care of that.

**Comment by annatraussnig** [comment]
Roles changed in the example query. @patrickvenetz can you have a mini look and confirm this is correct?

**Comment by patrickvenetz** [comment]
@annatraussnig LGTM

**Comment by patrickvenetz** [comment]
(`beginDate` was off, fixed already.)

**Comment by annatraussnig** [comment]
queries ran. thanks for helping with `beginDate` @patrickvenetz  :)
linking the components later today.
