### ISSUE TITLE
Feature request: provide interface to obtain API keys

### ISSUE THREAD

**Issue by dev-zero** [orbiting/backends#578]
There is a short description on how to obtain PDFs for articles (or different data via GraphQL) here: https://www.republik.ch/2018/09/01/app/diskussion but without further info on how to obtain the `connect.sid`.
While I can pull this out of an authenticated browser, this would tie my scripts livetime to the browser cookie, correct?
In that regard it would be really nice if the frontend could provide a tab/form to generate named API keys instead.

**Comment by patrickvenetz** [comment]
Yes, it would tie your script to your browser session.

There are no plans to provide and interface to generate access tokens (we just don't need it just yet).

Until we can provide you with a kind interface to issue access tokens, you could issue and authorize a session cookie soley for your script. Think of it as an access token or API key you will authorize to act on your behalf.

First, sign in with your email address (using `curl` to post HTTP requests to API).

```sh
$ curl 'https://api.republik.ch/graphql' \
  -H 'Content-Type: application/json' \
  --data-raw '{"query":"mutation signIn($email: String!) { signIn(email: $email) { phrase expiresAt tokenType }}","variables":{"email":"your@email.address"}}' \
  -v
```

API will respond with a session cookie in header and some additional info as JSON in body:

```sh
> POST /graphql HTTP/1.1
[...]
< Set-Cookie: connect.sid=sessionid.withsignature; Domain=republik.ch; [...]
[...]
{"data":{"signIn":{"phrase":"famos betören Lunte","expiresAt":"2021-03-31T07:37:00.904Z","tokenType":"APP"}}}
```

Keep `connect.sid` cookie value API returned in `Set-Cookie` header.

`tokenType` in response body is hinting whether API expects session to be authorized via email with a confirmation link (`EMAIL_TOKEN`) or via app (`APP`).

By then, you should either have received an email or a popover screen in your Republik-App. This is the authorization part, where we expect human interaction.

Once you authorize that session, you are able query API using `connect.sid` cookie.

A fairly easy check is to query `me.id`:

```sh
$ curl 'https://api.republik.ch/graphql' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: connect.sid=sessionid.withsignature' \
  --data-raw '{"query":"{ me { id } }"}'
```

Response should look like this:

```sh
{"data":{"me":{"id":"your-uuid-user-id"}}}
```

This is in a nutshell what [republik-frontend](https://github.com/orbiting/republik-frontend) does.

**Comment by dev-zero** [comment]
@patrickvenetz seems to work perfectly, thanks a lot! Since I'm planning on writing a little script in Python which pulls the new articles as PDFs on to my [Remarkable tablet](https://remarkable.com/) I'm using the following Python snippet:


```python
import requests

API_URL_REPUBLIK = 'https://api.republik.ch/graphql'

def request_token(email: str):
    """ Request a new session token (connect.sid) from the REPUBLIK GraphQL API,
        required to issue further requests.
    """
    resp = requests.post(API_URL_REPUBLIK, json={
        "query": "mutation signIn($email: String!) { signIn(email: $email) { phrase expiresAt tokenType }}",
        "variables": {
            "email": email,
            },
        })

    resp.raise_for_status()

    connect_sid = resp.cookies['connect.sid']
    signin_data = resp.json()['data']['signIn']

    return connect_sid, signin_data
```
