### ISSUE TITLE
PROLONG Page should display previous price

### ISSUE THREAD

**Issue by ovbm** [orbiting/backends#684]
- [ ] Prolong userPrice=true, change copy of going back to regular price
<img width="572" alt="Screenshot 2021-11-24 at 15 09 59" src="https://user-images.githubusercontent.com/20746301/143253823-b0efbfb1-6ad6-40bc-bb31-f6289f7a8e0b.png">

**Comment by pae-blue** [comment]
Fixed by https://github.com/orbiting/backends/pull/690
